// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'categorial-tags-column-name'
  | 'categorial-tags-dialog-title'
  | 'categorial-tags-dialog-title-error'
  | 'categorial-tags-dialog-title-info'
  | 'categorial-tags-dialog-title-warning'
  | 'categorial-tags-no-selection-hint'
  | 'categorial-tags-selection-titles'
  | 'pref-dialog-capture-shortcut-button'
  | 'pref-dialog-capture-shortcut-label'
  | 'pref-dialog-open-shortcut-key-description'
  | 'pref-dialog-open-shortcut-key-label'
  | 'pref-help'
  | 'prefs-title';
