import { config } from "../../package.json";

/**
 * Preference keys of this plugin, generated by `zotero-plugin-scaffold`
 * into `typings/prefs.d.ts`.
 */
export type PluginPrefsMap = _ZoteroTypes.Prefs["PluginPrefsMap"];

/**
 * Get preference value.
 * Wrapper of `Zotero.Prefs.get`.
 * @param key
 */
export function getPref<K extends keyof PluginPrefsMap>(
  key: K,
): PluginPrefsMap[K] | undefined {
  return Zotero.Prefs.get(`${config.prefsPrefix}.${String(key)}`, true) as
    PluginPrefsMap[K] | undefined;
}

/**
 * Set preference value.
 * Wrapper of `Zotero.Prefs.set`.
 * @param key
 * @param value
 */
export function setPref<K extends keyof PluginPrefsMap>(
  key: K,
  value: PluginPrefsMap[K],
): void {
  Zotero.Prefs.set(`${config.prefsPrefix}.${String(key)}`, value, true);
}

/**
 * Clear preference value.
 * Wrapper of `Zotero.Prefs.clear`.
 * @param key
 */
export function clearPref(key: keyof PluginPrefsMap): void {
  Zotero.Prefs.clear(`${config.prefsPrefix}.${String(key)}`, true);
}
